import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import Card from '../components/Card'
import Image from 'next/image'

import data from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  console.log("getStaticProps")
  return {
    props: {
      coffeeStores: data
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  console.log("props", props)

  const handleOnBannerBtnClick = () => {
    console.log("Hello there, General Kenobi")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header 
          buttonText="View stores nearby" 
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage} >
          <Image 
            src='/static/mega-creator-1.png'
            width={900}
            height={450}
            alt='hero image'
            />
        </div>
        <div className={styles.sectionWrapper}>
          {props.coffeeStores.length > 0 ? 
          <h2 className={styles.heading2}>Stores Near Me</h2> :
          <h2 className={styles.heading2}>No Coffee Stores found!</h2>
          }
          <div className={styles.cardLayout}>
            {props.coffeeStores.map(coffeeStore => (
              <Card
                key={coffeeStore.id}
                href={`/coffee-store/${coffeeStore.id}`}
                cardLink={coffeeStore.websiteUrl}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl}
              />
              )
            )}
          </div>
        </div>
      </main>
    </div>
  )
}
