import Head from 'next/head'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import Card from '../components/Card'
import Image from 'next/image'

import { fetchCoffeeStores } from '../lib/coffee-stores';
import useTrackLocation from '../hooks/use-track-location'

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores: coffeeStores
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  const { handleTrackLocation, latLong, locationErrorMessage, findingLocation } = useTrackLocation();

  const handleOnBannerBtnClick = () => {
    console.log("Hello there, General Kenobi")
    handleTrackLocation();
  }

  const [coffeeStores, setCoffeeStores] = useState("")
  const [coffeeStoresError, setCoffeeStoresError] = useState(null)

  console.log({ latLong, locationErrorMessage })

  useEffect(async () => {
    if(latLong){
      try {
        const fetchedCoffeeStores = await fetchCoffeeStores(latLong, 30)
        setCoffeeStores(fetchedCoffeeStores)
        console.log({ fetchedCoffeeStores })
      } catch (error) {
        console.log({error})
        setCoffeeStoresError(error)
      }
    }
  },[latLong])

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header 
          buttonText={findingLocation ? "Locating...": "View stores nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        {locationErrorMessage &&
        <p>Something went wrong: {locationErrorMessage}</p>}
        {coffeeStoresError &&
        <p>Something went wrong: {coffeeStoresError}</p>}
        <div className={styles.heroImage} >
          <Image 
            src='/static/mega-creator-1.png'
            width={900}
            height={450}
            alt='hero image'
            />
        </div>
        {coffeeStores.length ?
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores Near Me</h2> 
            <div className={styles.cardLayout}>
              {coffeeStores.map(coffeeStore => (
                <Card
                  key={coffeeStore.id}
                  href={`/coffee-store/${coffeeStore.id}`}
                  cardLink={coffeeStore.websiteUrl}
                  name={coffeeStore.name}
                  photoUrl={coffeeStore.photoUrl}
                />
                )
              )}
            </div>
          </div>
        :
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores Near Me</h2> 
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(coffeeStore => (
                <Card
                  key={coffeeStore.id}
                  href={`/coffee-store/${coffeeStore.id}`}
                  cardLink={coffeeStore.websiteUrl}
                  name={coffeeStore.name}
                  photoUrl={coffeeStore.photoUrl}
                />
                )
              )}
            </div>
          </div>
        }
      </main>
    </div>
  )
}
